unique_ids:
  assets:
    menu.html: JEU4WN6EKVHPPS277B6E2WV2CR5QEKRS
    pos_mesero.js: FQMAU2VTY7WLIN5LJSGNGVBSOSAOUT3Q
    standard-page.html: ZG3CH43UINNPSYVYDUAPNVUIKLLLBUQ7
    theme.css: BABMBJRVSJA3SPOO4U7IHA6TIN27CWQ5
  forms:
    AdminMenu: WTJJRXFF6FAF2SANSZHRW4F7KR3H7XMA
    ClientesLealtad: BIHUYO33EA2CZHH2BYTDHH4M4HJ5VRZZ
    Menu: TTVWA4DDL3HAUME3Y5MGPAAURC7GDXSJ
    MonitorCocina: VO5GIJETINQK3I6QHMPGLXNGXMZOVDOS
    MonitorFiscal: UV7QGHD333KEVFOQAB3JB7TODUT6URPQ
    POSMesero: BVTQMNYG3WE4MO6VY4QFUGEJUYEAHUOM
  modules: {}
  scripts:
    generar_qrs_portavasos: VOYMNEJQQTRRGOOOONSFFVP2LMSVALTF
  server_modules:
    ServerModule1: FE4LGYQYXT3FOJFM7K7VKJ7WHVXU5N77
