unique_ids:
  assets:
    menu.html: BBMVHN3P6X6FDPQLJLZDLMMB36P52QNY
    standard-page.html: DVQYSQ7MI3KDYLLBTB5L7OL22QUY4WQ3
    theme.css: 3CGMZ5G4OWDUSMNYHWERSWIYIMOP56MF
  forms:
    ClientesLealtad: TLXSBTE34O5MXOP3VQYLWJL6I3UUGAD4
    Menu: TTVWA4DDL3HAUME3Y5MGPAAURC7GDXSJ
    MonitorCocina: 462633RPW6WR4FLJNTQY6B66MAGTQ7L5
    MonitorFiscal: GTM42UUK2RH7K6VILTSOBVHAT2YQA4YW
    POSMesero: LZNHHYPHYMN6N4ANLOSRLQ6OJJERXWG3
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: FE4LGYQYXT3FOJFM7K7VKJ7WHVXU5N77
